mp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView



from django.contrib import admin

from front.views import (
    teacherprofile,
    studentprofile,
    recieve_comment,
    searchoffer,
    searchneed,
    home,
    comment_posted,
    SignupTeacherView,
    newteacherprofile,
    editteacherprofile,
    ajax_new_skill,


)


urlpatterns = [
    url(r"^admin/", include(admin.site.urls)),
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^account/signup/teacher/$", SignupTeacherView.as_view(), name="teacher_signup"), 
    url(r"^newteacherprofile/$", newteacherprofile, name="new_teacher_profile"),      
    url(r"^account/", include("account.urls")), #pinax urls

    url(r"^recieve_data/", recieve_comment, name="recieve_comment"),
    
    url(r"^teacherprofile/(?P<teacher_id>\d+)/$", teacherprofile, name="teacherprofile"),
    url(r'^editteacherprofile/$', editteacherprofile, name="editteacherprofile"),
    url(r"^studentprofile/$", studentprofile, name="studentprofile"),
    url(r"^searchoffer/$", searchoffer, name="searchoffer"),
    url(r"^searchneed/$", searchneed, name="searchneed"),
    url(r"^home/$", home, name="homesite"),
    url(r'^comments/posted/$', comment_posted, name="commentposted"),
    url(r'^comments/', include("django_comments_xtd.urls")),
    url(r'^ajax/skills/new/$', ajax_new_skill, name="ajax-new-skill"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_comments_xtd.models import XtdComment

# Create your models here.



class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(null=True, help_text=u'Sube una foto de no mas de 2mb y de una resolución maxima 1280x1280.')
    headline = models.CharField(max_length=200, help_text=u'Breve description de hasta 200 caracteres.')
    about = models.TextField(help_text=u'Cuentales a tus alumnos por que deberian tomar la clase contigo')
#    position = GeopositionField()
    fee = models.FloatField(help_text=u'El monto minimo es $CL2.000 y maximo es $CL50.000 por hora')
    stars = models.IntegerField(blank=True, null=True)
    skills = models.ManyToManyField("Skill", help_text=u'Cuentanos en que asignaturas quieres ser profesor')

#    ping = models.DateTimeField(default=timezone.now)
#    lastseen = models.DateTimeField(default=timezone.now)

class Skill(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return "%s" % self.name


class SlimComment(XtdComment):
    title = models.CharField(max_length=256)

front/forms.py
# -*- coding: utf-8 -*-


from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.files.images import get_image_dimensions

from django_comments_xtd.forms import XtdCommentForm
from django_comments_xtd.models import TmpXtdComment
from django.contrib.auth.models import User
from front.models import Teacher

import account.forms

from django.shortcuts import get_object_or_404

from django import forms


import account.forms
from django.forms.extras.widgets import SelectDateWidget

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ('photo', 'headline', 'about', 'fee', 'skills')
        widgets = {
            'photo': forms.FileInput(),
            'headline': forms.TextInput(attrs={'class': 'form-control'}),
            'about': forms.Textarea(attrs={'class': 'form-control'}),
            'skills': forms.SelectMultiple(attrs={'class': 'chosen-select',
                                                  'data-placeholder': "Selecciona tus habilidades...",
                                                  'style': "width:450px;",
                                                  'tabindex': "2"}),
            'fee': forms.NumberInput(attrs={'class': 'touchspin2'}),
   #         'neighborhood': forms.TextInput(attrs={'class': 'form-control', 
   #                                         'placeholder': "Por ejemplo: Ñuñoa, Las condes, Santiago Centro",}),

        }
        error_messages = {
            'photo': {'required': 'Debe proporcionar una Imagen para su perfil.',
                      'invalid': 'Imagen Invalida'
                      },
            'headline': {'required': 'Debe proporcionar un Extracto para su perfil.',
                         },
            'about': {'required': 'Debe proporcionar Información sobre sus conocimientos.',
                      },
            'skills': {'required': 'Debe proporcionar por lo menos una Habilidad.',
                       'invalid': 'Habilidad Invalida'
                       },
            'fee': {'required': 'Debe proporcionar una tarifa por hora.',
                    'invalid': 'Tarifa Invalida'
                    }
        }

    def clean_fee(self):
        fee = float(self.cleaned_data.get('fee', False))
        if fee < 2000:
            raise forms.ValidationError("El monto minimo es $CL2000")
        elif fee > 50000:
            raise forms.ValidationError("El monto maximo es $CL50000")
        return fee

    def clean_photo(self):
        image = self.cleaned_data.get('photo', False)
        if image:
            if image.size > 2*1024*1024:
                raise forms.ValidationError("La imagen es muy grande, debe tener un tamaño menor a 2 mb")
            w, h = get_image_dimensions(image)
            if w > 1280 or h > 1280:
                raise forms.ValidationError("La imagen debe tener una resolución maxima de 1280x1280 pixeles")

        return image



class SlimCommentForm(XtdCommentForm):


    def get_comment_create_data(self):
        data = super(SlimCommentForm, self).get_comment_create_data()
        return data


    def clean_url(self):

        message = self.cleaned_data['url']
        message = "http://www.mejorpromedio.cl"
        return message

    def clean_name(self):
        data = self.cleaned_data['object_pk']
        user=User.objects.get(pk=data)
        #teacher = get_object_or_404(Teacher, "1")
        message = user.username
        #message = teacher.user.username
        return message

    def clean_userpk(self):
        data = self.cleaned_data['object_pk']
        user=User.objects.get(pk=data)
        #teacher = get_object_or_404(Teacher, "1")
        message = user.id
        #message = teacher.user.username
        return message

SlimCommentForm.base_fields.pop('url')

front/views.py
from django.shortcuts import get_object_or_404, render, redirect
from urlparse import urlsplit
from django import forms
from django.http import (
    Http404,
    HttpResponseRedirect,
    JsonResponse,
    HttpResponse,
)
from django.db import connection
from django.db.models import Q

from django.utils.crypto import get_random_string
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse

from front.models import (
    Teacher,
    Skill,
)
from front.forms import TeacherForm
import account.views

import front.forms


@csrf_exempt
@login_required
def ajax_new_skill(request):
    """ It gets a name and creates a skill with the name given
    """
    skill = None
    if request.method == 'POST':
        skill_name = request.POST.get('skillName', None)
        if skill_name:
            skill, created = Skill.objects.get_or_create(name=skill_name)
        return JsonResponse(
            {'skill_name': skill.name,
             'skill_id': skill.pk,
             'created': created}
        )


class SignupTeacherView(account.views.SignupView):


   def get_success_url(self, **kwargs):
        
        return "/newteacherprofile/"


@login_required
def newteacherprofile(request):
    """
       Manage singup of second step to teacher
    """
    teachform = TeacherForm(request.POST or None, request.FILES or None)


    if request.method == 'POST':
        if teachform.is_valid():
            try:
                teacherM = Teacher.objects.get(user=request.user)
            except:
                teacherM = teachform.save(commit=False)
                teacherM.user = request.user
                teacherM.save()
                skills = teachform.cleaned_data['skills']
                for skill in skills:
                    teacherM.skills.add(skill)
            else:
                teachform = TeacherForm(request.POST or None, request.FILES or None, instance=teacherM)
                teachform.save()
                           

            return HttpResponseRedirect(reverse('teacherprofile', args=(teacherM.id,)))
    return render(request, "newteacherprofile.html", locals())



def comment_posted( request ):
    referer = request.META.get('HTTP_REFERER', None)
    if referer is None:
        pass
    try:
        redirect_to = urlsplit(referer, 'http', False)[2]
    except IndexError:
       pass
    return HttpResponseRedirect(redirect_to)



def teacherprofile(request, teacher_id):
    """
        return teacher profile
    """
    teacher = get_object_or_404(Teacher, pk=teacher_id)

    teachers = Teacher.objects.all()    # this is to get information of all users for display comments.

    return render(request, "teacherprofile.html", locals())



@csrf_exempt
def recieve_comment(request):
    teachers = Teacher.objects.all()
    return render(request, "recieve_form.html", locals())




@login_required
def editteacherprofile(request):
    """
       Edit teacher profile
    """
    if hasattr(request.user, "teacher"):
        usrform = TeacherForm(instance=request.user)
        teacher = Teacher.objects.get(user=request.user)
        teachform = TeacherForm(instance=teacher)

    return render(request, "newteacherprofile.html", locals())

def studentprofile(request):
    """
        return how it works page
    """
    return render(request, "studentprofile.html", locals())


def searchoffer(request):
    """
        return how it works page
    """

    teachers = Teacher.objects.all()#.order_by('-lastseen')
    if request.GET.get("search", False):
        if connection.vendor == "postgresql":
            teachers = Teacher.objects.filter(Q(skills__name__unaccent__contains=request.GET.get("search")) |
                                              Q(about__unaccent__contains=request.GET.get("search")) |
                                             # Q(neighborhood__unaccent__contains=request.GET.get("search")) |
                                              Q(headline__unaccent__contains=request.GET.get("search"))
                                              ).distinct()
        else:

            teachers = Teacher.objects.filter(Q(skills__name__contains=request.GET.get("search")) |
                                              Q(about__contains=request.GET.get("search")) |
                                             # Q(neighborhood__contains=request.GET.get("search")) |
                                              Q(headline__contains=request.GET.get("search"))
                                              ).distinct()

    return render(request, "searchoffer.html", locals())

def searchneed(request):
    """
        return how it works page
    """
    return render(request, "searchneed.html", locals())

def home(request):
    """
        return how it works page
    """
    return render(request, "home.html", locals())

front/templates/_teacherbox.html
{% load comments %}
{% get_comment_count for teacher.user as comment_count %}


      <div class="col-sm-4">  
        <div class="well">
          <div class="well profile">
            <h4><a href="{% url 'teacherprofile' teacher.id %}">{{teacher.user.username }}</a></h4>
            <img src="{% if teacher.photo %}
            {{ teacher.photo.url }}
            {% else %}
            /static/images/icon.svg
            {% endif %}" class="img-circle" height="80" width="80" alt="Avatar">
          </div>


          <div class="caption">
              
              
              </h4>
              <div class="well profile">
              <p style="min-height: 60px">{{teacher.headline }}</p>
              </div>
          </div>
          <div class="well profile">
            
            <p style="min-height: 20px">
              {% for tag in teacher.skills.all  %}
                 <span class="label label-warning">{{tag.name}}</span>
              {% endfor %}
            </p>
          </div>

          <div class="ratings">
              <p style="margin-top:-15px"  class="pull-left big-font">${{teacher.fee|floatformat}}/Hora</p>
              <p style="margin-top:-15px" class="pull-right big-font">
                  {{ comment_count }}
                   <span class="glyphicon glyphicon-comment"></span>
               </p style="min-width=30px;">

 

          </div>

        </div>
      </div>

front/templates/home.html
{% extends "site_base.html" %}
{% load staticfiles %}
<head>

{% block head_title %}pinax-project-account{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>


{% block body_class %}home{% endblock %}

{% block body_base %}



<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators 
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    -->
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="{% static 'images/image_03.jpg' %}" alt="Image">

        <div class="carousel-caption">
          <h1>Profesores al alcance de un click</h1>
          <p>Clases particulares</p>
        </div>      
      </div>
<!--
      <div class="item">
        <img src="{% static 'images/image_02.png' %}" alt="Image">
        <div class="carousel-caption">
          <h1>Profesores al alcance de un click</h1>
          <p>Money Money.</p>
        </div>      
      </div>
    </div>

-->

<div class="row search">
  <div id="searchForm" class="col-xs-8 col-xs-offset-2">
  <form  role="form" action="/searchoffer/" method="get">
    <div class="input-group">
      <input type="text" placeholder="Busca tu clase!" name="search" value="{{request.GET.search}}" class="form-control input-lg">

      <div class="input-group-btn">
        <button class="btn btn-lg btn-success" type="submit">Buscar</button>
      </div>
    </div>
  </form>
  </div>
</div>








    <!-- Left and right controls 
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    -->
</div>
  
<div class="container text-center">    
  <h3>What We Do</h3><br>
  <div class="row">
    <div class="col-sm-4">
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Current Project</p>
    </div>
    <div class="col-sm-4"> 
      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
      <p>Project 2</p>    
    </div>
    <div class="col-sm-4">
      <div class="well">
       <p>Some text..</p>
      </div>
      <div class="well">
       <p>Some text..</p>
      </div>
    </div>
  </div>
</div><br>


{% endblock %}

front/templates/newteacherprofile.html
{% extends "site_base.html" %}

{% load account_tags %}
{% load i18n %}
{% load bootstrap %}
{% load staticfiles %}
{% block head_title %}{% trans "Regístrate" %}{% endblock %}

{% block csslibs %}
<link href="{% static 'css/plugins/chosen/chosen.css' %}" rel="stylesheet">
<link href="{% static 'css/plugins/touchspin/jquery.bootstrap-touchspin.min.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <form id="signup_form" method="post" action="{% url "new_teacher_profile" %}" autocapitalize="off" {% if teachform.is_multipart %} enctype="multipart/form-data"{% endif %}>
                <legend>{% trans "Regístrate" %}</legend>
                {% csrf_token %}
                               <form class="form-horizontal" action="/newteacherprof/" enctype="multipart/form-data" method="post">
                    {% csrf_token %}

                    {% if teachform.errors %}
                    <div class="alert alert-danger">
                        {% for error in teachform.errors.viewvalues %}
                            {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}


                    <div class="form-group">
                        <label class="col-sm-4 control-label">Imagen de Perfil</label>

                        <div class="img-preview img-preview-sm col-sm-10">
                         
                            <img id="blah"
                            src={% if teacher.photo %}"{{ teacher.photo.url }}"{%else%}"{% static 'images/icon.svg' %}"{% endif %}
                            width="100" height="100" />
                            <div class="btn-group">
                                <label title="{{teachform.photo.help_text}}"  for="id_{{ teachform.photo.name }}" class="btn btn-primary">
                                <!-- <input type='file' id="imgInp" class="hide" />-->
                                <div style="display: none"> {{ teachform.photo }} </div>Elegir Imagen</label>
                                


                            </div>

                            <span class="help-block">{{ teachform.photo.help_text}}</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Extracto</label>
                        <div class="col-sm-10">{{ teachform.headline }}
                            <span class="help-block">{{ teachform.headline.help_text}}</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Describe tu perfil como profesor</label>
                        <div class="col-sm-10">{{ teachform.about }}
                            <span class="help-block">{{ teachform.about.help_text}}</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Clases que dictarás</label>
                        <div class="col-sm-10">{{ teachform.skills }}
                            <span class="help-block">{{ teachform.skills.help_text}}</span>
                            <span class="help-block extra-info"></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Tarifa</label>
                        <div class="col-sm-10">{{ teachform.fee }}
                            <span class="help-block">{{ teachform.fee.help_text}}</span>
                        </div>
                    </div>

                    <div class="form-group pull-left">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button type="submit" class="btn btn-primary block m-b">Guardar Perfil</button>
                        </div>
                    </div>
                {% if redirect_field_value %}
                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}
                </form>


        </div>

    </div>
{% endblock %}

{% block jslibs %}
<!-- Chosen -->
<script src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>
<script src="{% static 'js/plugins/touchspin/jquery.bootstrap-touchspin.min.js' %}"></script>

{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#id_username').focus();


            function readURL(input) {

                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $('#blah').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#id_{{teachform.photo.name}}").change(function() {
                readURL(this);
            });

            var config = {
                no_results_text: 'Click aqui para agregar nueva skill',
                allow_single_deselect: true,
                disable_search_threshold: 10
            }

            var $chosenSkills = $('.chosen-select').chosen(config);

            // clicking in no results line will trigger the save()
            $(document).on('click', '.no-results', function(){
                $this = $(this);


                $.ajax({
                    url: "{% url 'ajax-new-skill' %}",
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        skillName: $('span', this).html()
                    }
                }).done(function(response) {

                    var $chosenContainer = $this.parents('.chosen-container');
                    var $ulOfChosens = $chosenContainer.find('.chosen-choices');
                    var last = Number($ulOfChosens.find('li.search-choice').last().find('a').data('option-array-index'));
                    var noResults = $this;

                    // showing a confirmation message
                    $chosenContainer
                        .siblings('.extra-info')
                        .html(response.skill_name + ' ha sido agregada a la lista.');

                    // adding new skill to original select
                    var $origSelect = $('#id_skills');
                    var $newOption = $(new Option(response.skill_name, response.skill_id, true));
                    $origSelect.append($newOption);

                    // $('.chosen-select').trigger("chosen:updated");
                    // $chosenContainer.removeClass('chosen-with-drop');
                    // $chosenContainer.removeClass('chosen-container-active');
                    $chosenSkills.chosen("destroy");
                    $chosenSkills.chosen({no_results_text: 'Click aqui para agregar nueva skill'});
                    
                    var elegidos = $('.chosen-select').val();
                    if (typeof elegidos != "undefined" && elegidos != null && elegidos.length > 0) {
                        elegidos.push(response.skill_id);
                      } else {
                        var elegidos = [response.skill_id];
                    }
                    $('.chosen-select').val(elegidos);
                    $('.chosen-select').trigger("chosen:updated");


                    //var text = '<li class="search-choice"><span>' + response.skill_name + '</span><a class="search-choice-close" data-option-array-index="' + response.skill_id + '"></a></li>';
                    
                    // // adding new skill to chosen list and clear typed text
                    // $ulOfChosens
                    //     .find('li.search-field')
                    //     .before('<li class="search-choice"><span>'+ response.skill_name +'</span><a class="search-choice-close" data-option-array-index="'+ (last + 1) +'"></a></li>');
                    // // clearing typed text
                    // $ulOfChosens
                    //     .find('input')
                    //     .val('');
                })
            });

            $(".touchspin2")
                .TouchSpin({
                    min: 1,
                    max: 6000000,
                    step: 0.5,
                    decimals: 2,
                    boostat: 5,
                    maxboostedstep: 10,
                    prefix: '$CL/h',
                    buttondown_class: 'btn btn-white',
                    buttonup_class: 'btn btn-white'
                });
            
        });
    </script>
{% endblock %}

front/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

        /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }

    .profile {
      background-color: #fff;
   
    }
  </style>


</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Messages</a></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group input-group">
          <input type="text" class="form-control" placeholder="Search..">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>        
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> My Account</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container text-center">    
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well profile">
        <p><a href="#">My Profile</a></p>
        <img src="http://image.flaticon.com/icons/svg/53/53119.svg" class="img-circle" height="65" width="65" alt="Avatar">
      </div>
      <div class="well profile">
        <p><a href="#">Interests</a></p>
        <p>
          <span class="label label-default">News</span>
          <span class="label label-primary">W3Schools</span>
          <span class="label label-success">Labels</span>
          <span class="label label-info">Football</span>
          <span class="label label-warning">Gaming</span>
          <span class="label label-danger">Friends</span>
        </p>
      </div>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><strong>Ey!</strong></p>
        People are looking at your profile. Find out who.
      </div>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
    </div>
    <div class="col-sm-7 text-left">
    
      <hr>

      <h4>Leave a Comment:</h4>
      <form role="form">
        <div class="form-group">
          <textarea class="form-control" rows="3" required></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
      <br><br>
      
      <p><span class="badge">2</span> Comments:</p><br>
      
      <div class="row">
        <div class="col-sm-2 text-center">
          <img src="http://image.flaticon.com/icons/svg/53/53119.svg" class="img-circle" height="65" width="65" alt="Avatar">
        </div>
        <div class="col-sm-10">
          <h4>Anja <small>Sep 29, 2015, 9:12 PM</small></h4>
          <p>Keep up the GREAT work! I am cheering for you!! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <br>
        </div>
        <div class="col-sm-2 text-center">
          <img src="http://image.flaticon.com/icons/svg/53/53119.svg" class="img-circle" height="65" width="65" alt="Avatar">
        </div>
        <div class="col-sm-10">
          <h4>John Row <small>Sep 25, 2015, 8:25 PM</small></h4>
          <p>I am so happy for you man! Finally. I am looking forward to read about your trendy life. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          <br>
          <p><span class="badge">1</span> Comment:</p><br>
          <div class="row">
            <div class="col-sm-2 text-center">
              <img src="http://image.flaticon.com/icons/svg/53/53119.svg" class="img-circle" height="65" width="65" alt="Avatar">
            </div>
            <div class="col-xs-10">
              <h4>Nested Bro <small>Sep 25, 2015, 8:28 PM</small></h4>
              <p>Me too! WOW!</p>
              <br>
            </div>
          </div>
        </div>
      </div>
      
    
    
    </div>
    <div class="col-sm-2 well">
      <div class="thumbnail">
        <p>Upcoming Events:</p>
        <img src="http://image.flaticon.com/icons/svg/53/53119.svg" alt="Paris" width="400" height="300">
        <p><strong>Paris</strong></p>
        <p>Fri. 27 November 2015</p>
        <button class="btn btn-primary">Info</button>
      </div>      
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>

</body>
</html>